=== yogeshydv5043/navi_mumbai_International_airport/target/classes/XSD/LoginEvent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- Root element: LoginEvent -->
    <xs:element name="LoginEvent">
        <xs:complexType>
            <xs:sequence>
                <!-- Header element with its sub-elements -->
                <xs:element name="Header" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sourceSystem" type="xs:string"/>
                            <xs:element name="DestinationSystem" type="xs:string"/>
                            <xs:element name="MessageType" type="xs:string"/>
                            <xs:element name="MessageSentDateTime" type="xs:dateTime"/>
                            <xs:element name="MessageSequenceNumber" type="xs:positiveInteger"/>
                            <xs:element name="TransactionIdentifier" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- CounterID element -->
                <xs:element name="CounterID" type="xs:string"/>

                <!-- User element -->
                <xs:element name="User" type="xs:string"/>

                <!-- AirlineID element -->
                <xs:element name="AirlineID" type="xs:string"/>

                <!-- LoginTime element -->
                <xs:element name="LoginTime" type="xs:dateTime"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== yogeshydv5043/navi_mumbai_International_airport/src/main/resources/XSD/LoginEvent.xml
<?xml version="1.0" encoding="UTF-8"?>
<LoginEvent xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="LoginEvent.xsd">
    <Header>
        <sourceSystem>NMIA.CUPPS</sourceSystem>
        <DestinationSystem>NMIA.IB</DestinationSystem>
        <MessageType>LoginEvent</MessageType>
        <MessageSentDateTime>2024-07-08T11:22:34Z</MessageSentDateTime>
        <MessageSequenceNumber>1323</MessageSequenceNumber>
        <TransactionIdentifier>1234abcd</TransactionIdentifier>
    </Header>
    <CounterID>NIACKB001</CounterID>
    <User>6E</User>
    <AirlineID>6E123</AirlineID>
    <LoginTime>2024-09-18T14:30:00Z</LoginTime>
</LoginEvent>
